base:
  log_level: INFO
  random_state: 42

data:
  data_path: data/hotel_reviews.csv
  data_train_path: data/train.csv
  data_val_path: data/val.csv
  data_test_path: data/test.csv

preprocess:
  test_train_split: 0.2
  model_name: "bert-base-uncased"
  max_length: 128

train:
  num_labels: 5 
  output_dir: results
  evaluation_strategy: "epoch"
  save_strategy: "epoch"
  logging_dir: './logs'
  logging_steps: 10
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  num_train_epochs: 3
  save_total_limit: 2
  push_to_hub: False

evaluate:
  model_path: models
  batch_size: 32
  shuffle: False
  num_workers: 2